"""Finalizer 节点 — 生成 final-report.md."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from ..codex_client import codex_exec
from ..config_loader import _hub_dir
from ..run_store import save_run_file, save_run_json


def build_finalizer_prompt(state: dict[str, Any]) -> str:
    """构建 finalizer prompt."""
    prompts_dir = _hub_dir() / "src" / "ai_workflow_hub" / "prompts"
    template = (prompts_dir / "finalizer.md").read_text(encoding="utf-8")

    context = f"""
## Run Info
- Run ID: {state.get("run_id", "")}
- Project: {state.get("project_name", "")} ({state.get("project_id", "")})
- Task: {state.get("task_title", "")} ({state.get("task_id", "")})
- Risk: {state.get("task_risk", "medium")}
- Mode: {'dry-run' if state.get("dry_run", True) else 'apply'}
- Branch: {state.get("current_branch", "")}
- Status: {state.get("status", "unknown")}

## Plan Summary
{state.get("plan", "")[:2000]}

## Execution Log
{state.get("execution_log", "")[:3000]}

## Test Results
{state.get("test_output", "")[:3000]}

## Review Verdict
{state.get("review_result", "")}

## Review Summary
{state.get("review_summary", "")}

## Diff Summary
- Files changed: {len(state.get("changed_files", []))}
- Diff lines: {state.get("diff_line_count", 0)}

## Safety Flags
- Dangerous: {state.get("dangerous_change", False)}
- Human Required: {state.get("human_required", False)}
"""
    return template + "\n\n" + context


def finalizer_node(state: dict[str, Any]) -> dict[str, Any]:
    """执行终结节点.

    生成 final-report.md，设置最终 status。
    """
    run_dir = state.get("run_dir", "")
    project_path = state.get("project_path", "")
    model = state.get("reviewer_model", "gpt-5.5-codex")  # 复用 reviewer 模型
    status = state.get("status", "passed")

    # 根据当前状态确定最终 status
    review_result = state.get("review_result", "")
    if review_result == "blocked":
        status = "blocked"
    elif state.get("human_required"):
        status = "human_required"
    elif review_result == "pass":
        status = "passed"
    elif review_result == "fail":
        status = "failed"

    from datetime import datetime, timezone
    state["status"] = status
    state["updated_at"] = datetime.now(timezone.utc).isoformat()

    # --- Finalizer: Codex → retry → local deterministic template ---
    trusted_for_status = True
    fallback_reason = ""
    final_backend = "codex_cli"

    prompt = build_finalizer_prompt(state)
    result = codex_exec(
        prompt=prompt, model=model, cwd=project_path, timeout=120,
        stdout_log=str(Path(run_dir) / "finalizer-stdout.log"),
        stderr_log=str(Path(run_dir) / "finalizer-stderr.log"),
    )

    if not result.get("stdout", "").strip() and result.get("backend") != "codex_cli":
        # Retry with compact factual prompt
        compact = _build_compact_prompt(state)
        result = codex_exec(
            prompt=compact, model=model, cwd=project_path, timeout=60,
            stdout_log=str(Path(run_dir) / "finalizer-retry-stdout.log"),
            stderr_log=str(Path(run_dir) / "finalizer-retry-stderr.log"),
        )

    report = result.get("stdout", "")
    final_backend = result.get("backend", "codex")
    fallback_from = result.get("fallback_from", "")

    if fallback_from or not report.strip():
        # Use local deterministic template — no model interpretation
        report = _generate_deterministic_report(state)
        fallback_reason = fallback_from or "empty output"
        trusted_for_status = False
        final_backend = "local_template"

        # Prefix with fallback warning
        report = (f"> Finalizer note: generated by local template (Codex {fallback_reason}).\n"
                  f"> Source of truth: state.json, safety-report.json, review.yaml, test-output.md.\n\n"
                  + report)

    save_run_file(run_dir, "final-report.md", report)
    save_run_json(run_dir, "state.json", state)
    _write_failure_analysis_if_needed(state)

    return {
        "status": status,
        "updated_at": state["updated_at"],
        "backend_calls": {
            "finalizer": {
                "backend": final_backend,
                "model": model,
                "exit_code": result.get("exit_code", -1),
                "stdout_log": str(Path(run_dir) / "finalizer-stdout.log"),
                "stderr_log": str(Path(run_dir) / "finalizer-stderr.log"),
                "fallback_from": fallback_from,
                "fallback_reason": fallback_reason,
                "trusted_for_status": trusted_for_status,
            }
        },
    }


def _generate_fallback_report(state: dict[str, Any]) -> str:
    """如果 Codex 不可用，生成基础报告."""
    backend_lines = _render_backend_calls(state.get("backend_calls", {}))
    return f"""# Final Report

## Run Info
- **Run ID**: {state.get("run_id", "")}
- **Project**: {state.get("project_name", "")} ({state.get("project_id", "")})
- **Task**: {state.get("task_title", "")} ({state.get("task_id", "")})
- **Risk**: {state.get("task_risk", "medium")}
- **Mode**: {'dry-run' if state.get("dry_run", True) else 'apply'}
- **Branch**: {state.get("current_branch", "")}
- **Status**: {state.get("status", "unknown")}
- **Started**: {state.get("created_at", "")}
- **Completed**: {state.get("updated_at", "")}

## Plan Summary
{state.get("plan", "No plan available.")[:1000]}

## Changes Summary
{chr(10).join(f'- {f}' for f in state.get("changed_files", [])) or 'No files changed.'}

## Test Results
Exit code: {state.get("test_exit_code", -1)}

## Review Verdict
{state.get("review_result", "")}

## Backend Calls
{backend_lines}

## Risk Assessment
Dangerous change: {state.get("dangerous_change", False)}
Human required: {state.get("human_required", False)}

## Evidence Files
All files in: {state.get("run_dir", "")}
"""


def _render_backend_calls(backend_calls: dict) -> str:
    """渲染 backend_calls 表格."""
    if not backend_calls:
        return "No backend calls recorded."
    lines = ["| Node | Backend | Model | Exit Code |", "|------|---------|-------|-----------|"]
    for node, info in backend_calls.items():
        if isinstance(info, dict):
            lines.append(f"| {node} | {info.get('backend', '?')} | {info.get('model', '?')} | {info.get('exit_code', '?')} |")
    return "\n".join(lines)


def _build_compact_prompt(state: dict[str, Any]) -> str:
    """超短 factual prompt for retry."""
    return f"""Summarize this run in 5 bullet points.

Status: {state.get('status','?')}
Review: {state.get('review_result','?')}
Tests: exit_code={state.get('test_exit_code',-1)}
Diff: {state.get('diff_line_count',0)} lines, {len(state.get('changed_files',[]))} files
Backend: {_backend_summary(state.get('backend_calls',{}))}

Format: one line per fact, no markdown headers."""


def _backend_summary(bc: dict) -> str:
    return ", ".join(f"{n}={i.get('backend','?')}" for n, i in bc.items() if isinstance(i, dict))


def _generate_deterministic_report(state: dict[str, Any]) -> str:
    """确定性报告 — 只拼硬事实，不依赖模型."""
    bc_table = _render_backend_calls(state.get("backend_calls", {}))
    changed = state.get("changed_files", [])
    return f"""# Final Report (deterministic)

## Run Info
- **Run ID**: {state.get("run_id", "")}
- **Project**: {state.get("project_name", "")}
- **Task**: {state.get("task_title", "")}
- **Risk**: {state.get("task_risk", "medium")}
- **Mode**: {'dry-run' if state.get("dry_run", True) else 'apply'}
- **Status**: {state.get("status", "unknown")}

## Review
- **Verdict**: {state.get("review_result", "")}

## Changes
{chr(10).join(f'- `{f}`' for f in changed) if changed else '- (none)'}

## Tests
- **Exit code**: {state.get("test_exit_code", -1)}

## Safety
- **Dangerous**: {state.get("dangerous_change", False)}
- **Human required**: {state.get("human_required", False)}

## Backend Calls
{bc_table}

## Evidence
All files in: {state.get("run_dir", "")}
"""


# ---------------------------------------------------------------------------
# Failure analysis
# ---------------------------------------------------------------------------

def _write_failure_analysis_if_needed(state: dict[str, Any]) -> bool:
    """终态 failed/blocked/human_required 时生成 failure-analysis.md."""
    status = state.get("status", "")
    if status not in ("failed", "blocked", "human_required"):
        return False

    content = build_failure_analysis(state)
    run_dir = state.get("run_dir", "")
    if run_dir:
        from ..run_store import save_run_file
        save_run_file(run_dir, "failure-analysis.md", content)
        return True
    return False


def build_failure_analysis(state: dict[str, Any]) -> str:
    """生成 failure-analysis.md."""
    status = state.get("status", "unknown")
    blocking_node = _infer_blocking_node(state)
    bc_table = _render_backend_calls_full(state.get("backend_calls", {}))
    next_action = _recommend_next_action(state, blocking_node)

    return f"""# Failure Analysis

## Summary
- **Status**: {status}
- **Review Result**: {state.get("review_result", "")}
- **Human Required**: {state.get("human_required", False)}
- **Error Message**: {state.get("error_message", "")[:200]}
- **Run ID**: {state.get("run_id", "")}
- **Task**: {state.get("task_title", "")} ({state.get("task_id", "")})
- **Project**: {state.get("project_name", "")}

## Likely Blocking Node
- **Node**: {blocking_node}
- **Reason**: {_blocking_reason(state, blocking_node)}

## Backend Calls
{bc_table}

## Diff State
- **Changed Files**: {len(state.get("changed_files", []))}
- **Diff Lines**: {state.get("diff_line_count", 0)}

## Test State
- **Test Exit Code**: {state.get("test_exit_code", -1)}

## Review State
- **Review Summary**: {state.get("review_summary", "")}
- **Next Fixes**: {', '.join(state.get("next_fixes", [])) or 'none'}

## Safety / Human Gate
- **Dangerous Change**: {state.get("dangerous_change", False)}
- **Human Required**: {state.get("human_required", False)}

## Recommended Next Action
{next_action}

## Evidence Files
All evidence in: {state.get("run_dir", "")}
"""


def _infer_blocking_node(state: dict[str, Any]) -> str:
    """推断阻塞节点."""
    err = state.get("error_message", "")
    if err and "timeout" in err.lower():
        bc = state.get("backend_calls", {})
        for node in ["executor", "fixer"]:
            info = bc.get(node, {})
            if isinstance(info, dict) and info.get("timed_out"):
                return node
        return "executor"

    if state.get("human_required"):
        return "human_gate"
    if state.get("review_result") == "blocked":
        return "reviewer"
    if state.get("fix_round", 0) >= state.get("max_fix_rounds", 3):
        return "fixer"
    if state.get("test_exit_code", 0) not in (0, -1):
        return "tester"
    if err:
        bc = state.get("backend_calls", {})
        for node in ["executor", "fixer"]:
            info = bc.get(node, {})
            if isinstance(info, dict) and info.get("exit_code", 0) != 0:
                return node
        return "executor"
    return "unknown"


def _blocking_reason(state: dict[str, Any], node: str) -> str:
    reasons = {
        "executor": "executor failed or timed out",
        "fixer": "fixer exhausted max rounds",
        "reviewer": "reviewer blocked the run",
        "human_gate": "human review required",
        "tester": "tests failed",
        "unknown": "blocking reason unclear",
    }
    return reasons.get(node, reasons["unknown"])


def _render_backend_calls_full(backend_calls: dict) -> str:
    if not backend_calls:
        return "No backend calls."
    lines = ["| Node | Backend | Model | Exit | Timeout | Dur(s) | Fallback |",
             "|------|---------|-------|------|---------|--------|----------|"]
    for node, info in backend_calls.items():
        if isinstance(info, dict):
            fb = info.get("fallback_from", "") or "-"
            lines.append(
                f"| {node} | {info.get('backend','?')} | {info.get('model','?')} | "
                f"{info.get('exit_code','?')} | {info.get('timed_out',False)} | "
                f"{info.get('duration_seconds','?')} | {fb} |")
    return "\n".join(lines)


def _recommend_next_action(state: dict[str, Any], node: str) -> str:
    actions = {
        "executor": "- Check OpenCode/Claude stdout/stderr logs\n- Retry with different backend: --coding-backend <other>\n- Verify API key and model availability",
        "fixer": "- Check fix rounds exhausted — task may need human intervention\n- Review diff changes and fix manually\n- Re-run apply after manual fix",
        "reviewer": "- Read review.md and review.yaml for blocking reasons\n- Fix the issues identified by reviewer\n- Re-run apply",
        "human_gate": "- Review human-gate.md\n- Approve: re-run with --apply\n- Reject: discard run",
        "tester": "- Check test-output.md for failures\n- Fix failing tests\n- Re-run apply",
        "unknown": "- Inspect all log files in run directory\n- Check state.json for details",
    }
    return actions.get(node, actions["unknown"])

